### PR TITLE
makes rfam compatible with parsing prman style .alf files

### PR DESCRIPTION
**Pull request by StephanGarbin**

### CODE REVIEW

**Review by thaines — CHANGES_REQUESTED** [review]
bin/add.py:

L24:
Should be "import .prman_AlfParser as alfParser" - no bin (absolute to relative import).

L107:
That's not how you handle a '::' - use the rfam.real() method instead.


node/node.py:

I'm confused by the lazy worker logic - shouldn't the number of active workers for both camps never excede self.config['processes']? It seems to be requesting the number of normal lazy workers, which means prman workers won't be counted against the process total!

Also, the whole code block regarding detecting if the prman workers are busy or not would be much better encapsulated, same as a normal worker, for readability.


node/prman_worker.py:
Probably should change that copyright message to this year and your name, or at least add your details, given how much of the file you have touched!

Haven't really read this file fully though - looks a bit hacky at points, and some of the command parsing looks like it might be fragile, but probably not worth messing with. Guess the main question is, have you tested it under Linux? :-)

**Comment by StephanGarbin** [comment]
Hey Tom,

Thanks for having a look!
made the changes you requested.. as for node.py: It's okay for the case of having a single worker per node, but I will amend for the general case.

yeah, command parsing is a little hacky but better than writing a whole new exporter.. this way we can use standard .alf files and benefit from updates that pixar makes :)

**Comment by StephanGarbin** [comment]
Oh and I haven't extensively tested this under Linux yet, I will do that on Monday at uni. I think this should be good though!

**Comment by StephanGarbin** [comment]
That last commit should fix the worker count bug for when a node can run more than one worker :)

**Review by thaines — APPROVED** [review]

**Pull request merged**
